version: '2'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=lutry-plaisance
  web:
    container_name: web-lutry-plaisance
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8082:80"
    links:
      - mysql
    environment:
      - VIRTUAL_HOST=<site>
      - XDEBUG_CONFIG=remote_host=192.168.1.163
    volumes:
      - ./docker/web/rewrite.conf:/etc/apache2/conf-enabled/rewrite.conf
    volumes_from:
      - data
    hostname: docker

  composer:
    build:
      context: ./
      dockerfile: ./docker/composer/Dockerfile
    volumes_from:
      - data
  npm:
   build:
     context: ./
     dockerfile: ./docker/npm/Dockerfile
   volumes_from:
     - data

  data:
    image: alpine:3.3
    volumes:
      - ./:/var/www/html/:rw
    entrypoint:
      - pwd
